### ISSUE TITLE
400 bad request and no memories when syncing local files

### ISSUE THREAD

**Issue by mdmohsin7** [BasedHardware/omi#1182]
- [ ] Sometimes 400 bad request when syncing local files
- [x] Updated and new memories response is empty even with YT video audio of more than 20 minutes

![CleanShot 2024-10-26 at 10 22 29@2x](https://github.com/user-attachments/assets/a9bca6d3-84d7-4836-a167-f7247e2cfafb)

**Comment by mdmohsin7** [comment]
<img width="558" alt="Screenshot 2024-10-27 at 7 41 25 PM" src="https://github.com/user-attachments/assets/a8ff2513-4632-42bc-a707-af75dfada091">

The reason for this 400 is that timestamp of the files is in the future

**Comment by beastoin** [comment]
@mdmohsin7 was it resolved with your last PR ? 😌

**Comment by mdmohsin7** [comment]
> @mdmohsin7 was it resolved with your last PR ? 😌

It still happens sometimes, the invalid timestamp issue, but not as frequently as it used to be

**Comment by beastoin** [comment]
not a priority for now, moving to the backlog

**Comment by mdmohsin7** [comment]
Closing it for now as it is not a priority at the moment
